title:             Htoo Eain Thin
email:             kokoye2007+htooeainthin@gmail.com
description:       HTOO EAIN THIN
author:            HET Big-Fans
#url:               "localhost:4000"
url:               "http://htooeainthin.github.io/"
baseurl:

# Social Profiles
#twitter_username:  SBootstrap
#github_username:   BlackrockDigital
#facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          10
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
